### ISSUE TITLE
Support for sub-sampled images

### ISSUE THREAD

**Issue by saket** [mxalbert1996/Zoomable#14]
I'm trying to build an image viewer that is capable of showing gigantic images. This will require me to use something like [SubSampledImage](https://github.com/tom5079/SubSampledImage) which wouldn't be compatible with `Zoomable` out of the box. Could `Zoomable` take in lambdas for updating the state of `SubSampledImage` instead of applying zoom & pan information directly onto its content?

Thanks for maintaining this library btw!

**Comment by mxalbert1996** [comment]
It seems that [SubSampledImage](https://github.com/tom5079/SubSampledImage) already provides zooming/panning gesture support. Is there any specific reason you want to use Zoomable and SubSampledImage together?

**Comment by saket** [comment]
It can only be used for displaying images. For GIFs and videos I'll be using something else. I was hoping to use the same consistent gestures for all kinds of media by using `Zoomable` for all of them.

**Comment by saket** [comment]
Closing this in favor of [telephoto](https://saket.github.io/telephoto/).
