### ISSUE TITLE
When is the next version coming?

### ISSUE THREAD

**Issue by matsudamper** [mxalbert1996/Zoomable#18]
I found this fork from https://github.com/Tlaster/Zoomable .

It has a lot of features, and the zoom gestures like PhotoView are intuitive and wonderful.

I need this commit. Now I use snapshot.  Are there any plans to releae the next version?
https://github.com/mxalbert1996/Zoomable/commit/2709bf2d3688dfcd17a35f73406ad03f26d9da35

I did not notice this fork. I implemented this function myself...
https://github.com/Tlaster/Zoomable/pull/17

**Comment by mxalbert1996** [comment]
[1.5.0](/mxalbert1996/Zoomable/releases/tag/1.5.0) released!

**Comment by matsudamper** [comment]
thank you!!!
