### ISSUE TITLE
Publish artifacts for iOS

### ISSUE THREAD

**Issue by mxalbert1996** [mxalbert1996/Zoomable#32]
iOS artifacts need to be built on macOS.

**Comment by panpf** [comment]
I recommend a similar image zooming library ZoomImage (https://github.com/panpf/zoomimage).

It perfectly supports Compose Multiplatform and Android View, supports zooming, panning, positioning, rotation, and subsampling of large images. It also integrates image loaders such as sketch, glide, picasso, coil, etc.

The most important thing is that it can zoom large images without memory overflow
