### ISSUE TITLE
Sticky zoom feature

### ISSUE THREAD

**Issue by StefanOltmann** [mxalbert1996/Zoomable#37]
I propose implementing a feature where the scaling and translation are synchronized across multiple `ZoomableState` objects within a `HorizontalPager` (where the `beyondBoundsPageCount` setting is higher than 0).

**Comment by mxalbert1996** [comment]
More context: https://kotlinlang.slack.com/archives/CJLTWPH7S/p1714039651982869

Here's what I came up with and it seems to work well.
https://gist.github.com/mxalbert1996/f5a4ab7dcc708ace8147e917dbf4a808
Does this solve your problem?

**Comment by StefanOltmann** [comment]
Yes, it works great! :)
Thank you a lot!
