### ISSUE TITLE
How to use correctly state.dismissDragProgress

### ISSUE THREAD

**Issue by mcfboss** [mxalbert1996/Zoomable#9]
I´m trying to use state.dismissDragProgress to lower the opacity of the zoomable when is dismissed, but after a rotation change or even sometimes just swiping to the next image the progress is not working anymore.

As example, took the example and added this line to the zoomable modifier : 

modifier = Modifier.alpha(1 - state.dismissDragProgress)

Is that the correct way of using it?

Thanks!

**Comment by mxalbert1996** [comment]
Yeah, generally it's the correct way, but using `Modifier.graphicsLayer { alpha = 1 - state.dismissDragProgress) }` should be more efficient.
I've updated the sample to include the usage of `dismissDragProgress`.
